# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: nails_development
  host: localhost 
  user: root
  password: root
  pool: 5
  timeout: 5000

# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
production:
  adapter: mysql2
  database: nails_development
  host: localhost 
  user: root
  password: root
  pool: 5
  timeout: 5000
